version: '3.8'
volumes:
  postgres_data:
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=melody
      - POSTGRES_PASSWORD=nccu306
      - POSTGRES_DB=graduation
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres