version: '3.8'
volumes:
  postgres_data:
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - postgres