version: '3.8'
services:
  postgres:
    image: postgres:latest
    ports:
      - 8080:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=melody
      - POSTGRES_PASSWORD=nccu306
      - POSTGRES_DB=graduation
  
  backend-services:
    build: .
    ports:
      - 3000:5000
    depends_on:
      - postgres